name: Hoga
description: "A new Flutter project."
publish_to: 'none'
version: 0.15.113+13

environment:
  sdk: ^3.7.0

dependencies:
  sentry_flutter: ^9.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.3.4
  meta: ^1.16.0
  bloc: ^9.0.0
  firebase_core: ^2.32.0
  firebase_analytics: ^10.8.0
  http: ^1.1.0
  dio: ^5.7.0
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.69.0
  share_plus: ^10.1.3
  screen_brightness: ^2.1.7
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  url_launcher: ^6.3.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  pretty_qr_code: ^3.5.0
  path_provider: ^2.1.4
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^18.0.1
  flutter_loading_overlay: ^1.0.3
  go_router: ^14.8.1
  marqueer: ^2.1.0
  story_view: ^0.16.6
  flutter_native_splash: ^2.4.7
  get_it: ^9.2.0
  

dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Fast testing packages
  mocktail: ^1.0.0
  bloc_test: ^10.0.0
  http_mock_adapter: ^0.5.0
  change_app_package_name: ^1.4.0
  integration_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  # Background color for the splash screen
  color: "#ffffff"
  color_dark: "#161C25"
  
  # Platforms
  android: true
  ios: true
  web: false
  
  # Splash image - using launcher icon for smaller size
  image: "assets/images/new_splash_logo.png"
  image_dark: "assets/images/new_splash_logo.png"
  
  # Image alignment - scaleAspectFit makes iOS icon smaller
  android_gravity: center
  ios_content_mode: scaleAspectFit
  
  # Fullscreen mode
  fullscreen: true
  
  # Android 12+ configuration
  android_12:
    # Background color
    color: "#ffffff"
    color_dark: "#161C25"
    
    # Center icon (launcher icon)
    image: "assets/images/android_icon.png"
    image_dark: "assets/images/android_icon.png"
    
    # Icon background color
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#161C25"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - shorebird.yaml
    - assets/images/
    - assets/images/onboarding/
    - assets/images/walk/
    - .env
  
  fonts:
    - family: Chillax
      fonts:
        - asset: assets/fonts/chillax/Chillax-Extralight.otf
          weight: 200
        - asset: assets/fonts/chillax/Chillax-Light.otf
          weight: 300
        - asset: assets/fonts/chillax/Chillax-Regular.otf
          weight: 400
        - asset: assets/fonts/chillax/Chillax-Medium.otf
          weight: 500
        - asset: assets/fonts/chillax/Chillax-Semibold.otf
          weight: 600
        - asset: assets/fonts/chillax/Chillax-Bold.otf
          weight: 700
    
    - family: Supreme
      fonts:
        - asset: assets/fonts/supreme/Supreme-Thin.otf
          weight: 100
        - asset: assets/fonts/supreme/Supreme-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/supreme/Supreme-Extralight.otf
          weight: 200
        - asset: assets/fonts/supreme/Supreme-ExtralightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/supreme/Supreme-Light.otf
          weight: 300
        - asset: assets/fonts/supreme/Supreme-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/supreme/Supreme-Regular.otf
          weight: 400
        - asset: assets/fonts/supreme/Supreme-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/supreme/Supreme-Medium.otf
          weight: 500
        - asset: assets/fonts/supreme/Supreme-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/supreme/Supreme-Bold.otf
          weight: 700
        - asset: assets/fonts/supreme/Supreme-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/supreme/Supreme-Extrabold.otf
          weight: 800
        - asset: assets/fonts/supreme/Supreme-ExtraboldItalic.otf
          weight: 800
          style: italic

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: konto-mobile-app
  org: kontoapp
